CREATE DATABASE MVC_HIBERNATE;
USE MVC_HIBERNATE;
DROP TABLE IF EXISTS USERDATA;
CREATE TABLE USERDATA
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FNAME VARCHAR(30) NOT NULL,
    LNAME VARCHAR(30),
    EMAILID VARCHAR(100) UNIQUE NOT NULL,
    USERNAME VARCHAR(30) UNIQUE NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
    C BOOLEAN DEFAULT FALSE,
    CPP BOOLEAN DEFAULT FALSE,
    JAVA BOOLEAN DEFAULT FALSE,
    HTML BOOLEAN DEFAULT FALSE,
    CSS BOOLEAN DEFAULT FALSE,
    JAVASCRIPT BOOLEAN DEFAULT FALSE,
    MYSQL BOOLEAN DEFAULT FALSE,
    REACT BOOLEAN DEFAULT FALSE
);

